package com.ari.j2ee.entitas;
// Generated Jul 16, 2016 11:10:49 PM by Hibernate Tools 4.3.1

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GeneratorType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "human_resource"
)
public class Users implements java.io.Serializable
{

    private int id;
    private String name;
    private String email;
    private String address;
    private String password;
    private Boolean newsletter;
    private String framework;
    private String sex;
    private Integer number;
    private String country;
    private String skill;

    public Users()
    {
    }

    

    public Users(int id)
    {
        this.id = id;
    }

    public Users(int id, String name, String email, String address, String password, Boolean newsletter, String framework, String sex, Integer number, String country, String skill)
    {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.password = password;
        this.newsletter = newsletter;
        this.framework = framework;
        this.sex = sex;
        this.number = number;
        this.country = country;
        this.skill = skill;
    }



    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    @Column(name = "name", length = 30)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "email", length = 50)
    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    @Column(name = "address")
    public String getAddress()
    {
        return this.address;
    }

    public void setAddress(String address)
    {
        this.address = address;
    }

    @Column(name = "password", length = 20)
    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    @Column(name = "newsletter")
    public Boolean getNewsletter()
    {
        return this.newsletter;
    }

    public void setNewsletter(Boolean newsletter)
    {
        this.newsletter = newsletter;
    }

    @Column(name = "framework", length = 500)
    public String getFramework()
    {
        return this.framework;
    }

    public void setFramework(String framework)
    {
        this.framework = framework;
    }

    @Column(name = "sex", length = 1)
    public String getSex()
    {
        return this.sex;
    }

    public void setSex(String sex)
    {
        this.sex = sex;
    }

    @Column(name = "NUMBER")
    public Integer getNumber()
    {
        return this.number;
    }

    public void setNumber(Integer number)
    {
        this.number = number;
    }

    @Column(name = "COUNTRY", length = 10)
    public String getCountry()
    {
        return this.country;
    }

    public void setCountry(String country)
    {
        this.country = country;
    }

    @Column(name = "SKILL", length = 500)
    public String getSkill()
    {
        return this.skill;
    }

    public void setSkill(String skill)
    {
        this.skill = skill;
    }

}
